### ISSUE TITLE
Possible to support Gigabyte's RGB Fusion?

### ISSUE THREAD

**Issue by Joshfindit** [dcerisano/RGB-LED-Motherboard-Header-Driver-App#2]
SDK: https://www.gigabyte.com/mb/rgb/sdk (precompiled dlls)

Specifically I'm looking at the Z370 HD3P

**Comment by dcerisano** [comment]
Please see my response [here](https://github.com/dcerisano/RGB-LED-Motherboard-Header-Driver-App/issues/1).

Basically you need the datasheet for your SIO chip to do this the easy way.
nagisa@msi-rgb did it the [hard way](https://kazlauskas.me/entries/i-reverse-engineered-a-motherboard.html).

However once you have the control strings, his code can be easily adapted (trivial).

The real issue is the risk of bricking your motherboard - poking the SIO is a mine field. That is why ports are protected memory in Windows.
