### ISSUE TITLE
Support for MSI Z370 TOMAHAWK motherboard?

### ISSUE THREAD

**Issue by DGxInfinitY** [dcerisano/RGB-LED-Motherboard-Header-Driver-App#3]
It uses the NCT6795D-W Super I/O chip. As far as I know it is compatible with msi-rgb but I could be wrong. Do you know.

**Comment by dcerisano** [comment]
I would say yes, but the W at the end is concerning. 

Make sure you boot into Windows first and run the MSI gaming app to initialise the rgb header, since msi-rgb does not do this. 

You will have to do this every time after you unplug the computer (which resets the SIO). Normal reboots and shutdowns do not reset the SIO.

The init sequence could be inlcuded in msi-rgb at a later date. It is just another  series of bytes sent to the SIO registers. You could use [RWEverything ](http://rweverything.com/)to detect and copy it.

**Comment by DGxInfinitY** [comment]
Is REEverything a utility on Windows to read the comms?

**Comment by DGxInfinitY** [comment]
So I'll be getting the rest of my components today so I'm going to install Linux and try. If it doesn't work correctly I'll load windows on a spare drive and make sure to install the aura sync software to get the sio chip properly initialized. Is RWEverything a program to detect and log commands sent by various interfaces in windows? Cuz I'm was trying to see if there was a way to manually include the code myself. I mean I am not a programmer but I can easily decipher code and modify it to fit needs so I can at least try.

**Comment by dcerisano** [comment]
Yes, RWEverything is exactly that.

You would use it to capture control bytes that the Aura software sends to the SIO port registers for the RGB header. Msi-rgb contains SIO control bytes captured from MSI's Mystic Sync Gaming App (Aura equivalent) .

Since you have the same SIO chip that MSI uses, the control bytes should theoretically be the same.

Please be advised that coding to the metal is very risky, since sending the wrong control bytes to SIO port registers can actually **brick your mobo**. Proceed with **caution**!
